version: '3'

services:

  traefik:
    image: traefik:1.7
    command: --docker --docker.exposedbydefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    labels:
      - traefik.enable=true
      - traefik.backend=app
      - traefik.frontend.rule=Host:app.beer
    env_file:
      - ./backend/.env
    environment:
      APACHE_DOCUMENT_ROOT: public/
      DATABASE_URL: mysql://db_user:db_password@mysql:3306/db_name
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./backend:/var/www/html:rw

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    labels:
      - traefik.enable=true
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:phpadmin.app.beer
    environment:
      PMA_HOST: mysql
      PMA_USER: db_user
      PMA_PASSWORD: db_password

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
    volumes:
      - "./front:/app"
    environment:
      HOST: 0.0.0.0
    depends_on:
      - backend

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./docker/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

volumes:
  mysql_data:
    driver: local